version: "3"
services:
  mysql:
    container_name: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    image: mysql:5.7
    command: --sql_mode="NO_ENGINE_SUBSTITUTION"
    networks:
      - mvc
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  mvc:
    external: true

volumes:
  mysql-data:
    driver: local
